### ISSUE TITLE
Is there danger in arranging the tiles in a more typical {zoom}/{x}/{y} format?

### ISSUE THREAD

**Issue by Taytay** [mapcrafter/mapcrafter#120]
Leaflet, and the other map packages, use something like this for their  default URL template:
'http://somedomain.com/blabla/{z}/{x}/{y}.png'
Where z is the zoom level.

Is there anything that would prevent mapcrafter from doing the same? Is it a matter of trying to keep an individual folder from having too many files in it, as would happen at the closer zoom levels?

**Comment by wesweaver** [comment]
I'll comment on this, even though it's been closed for almost a year because I think this brings up a good point.

I'd really like to use Mapcrafter generated top-down tiles in a Leaflet project that is _not_ the generated template, but the file structure is a quadtree, mapcrafterui.js is complex (though well commented), and I can't use normal Leaflet web mapping syntax in the template (i.e. `var drawnItems = new L.featureGroup(); Mapcrafter.addLayer(drawnItems);`) will not work.

I'm cool with the quadtree structure and the program is fantastic, but it would be really helpful to get some documentation on how to implement the tiles in a more standard Leaflet map.

**Comment by m0r13** [comment]
Theoretically it would be possible to change the output structure of the tiles, but I wouldn't support this. Are you really sure that you can't use the tiles in the structure they are? You could use the little code from the ``mapcrafterui.js`` (``MCTileLayer``) to add the tiles with their original structure to your custom Leaflet. Considering that your remaining layers are using the same coordinate system or you add some offset to the tiles, you could use them together with the Mapcrafter tiles.

Otherwise I can point out some locations in the code to you later where tiles are read and written, but you would have to do the conversion between the two tile structures yourself, I'm a bit too busy right now with other things now.

**Comment by wesweaver** [comment]
Thanks for the quick response. I'm not asking you to implement the {z}/{x}/{y} format at all. I think the structure you have is great, albeit a little over my head. I am trying to work with `MCTileLayer` code, but I haven't had much success yet. I'll keep working at it and if I figure it out, I'll contribute some documentation.

**Comment by m0r13** [comment]
No worries, I just meant I can point out some code locations to you if want to try implementing it. :)
