### ISSUE TITLE
Read last write time of chunk file instead of reading its contents

### ISSUE THREAD

**Issue by Cougar** [mapcrafter/mapcrafter#135]
20000x20000 has 1600 chunk files. In my system (using NFS) it takes about 50 sec just to read all chinks even if there is no change saved a long time. It could work much faster if chunk file last write times will be check before reading (and processing) them.

2015-03-07 19:27:28 [INFO] [default] Scanning worlds...
2015-03-07 19:28:15 [INFO] [default] [1/4] Rendering map map_world_day ("Day"):

**Comment by m0r13** [comment]
Those files are not chunk files. Those files are region files each containing 32x32 chunks. Also the region files are not completely read, only the header of those files containing the chunk timestamps is read when scanning the world.

There might be a little performance improvement, but in my experience the Minecraft server/client often touches region files / chunks quite randomly without an obvious modification by the player. Besides that the region file headers must be read to know which chunks even exist I don't think there would be a huge improvement rather than making the scanning code more complicated by also looking for region timestamps instead of chunk timestamps.
