### ISSUE TITLE
Debian no longer has dependencies

### ISSUE THREAD

**Issue by 33mhz** [mapcrafter/mapcrafter#138]
libjpeg-turbo8, libjpeg-turbo, and libjpeg8 aren't available in default Debian install -- can it be changed to allow use of libjpeg-turbo-progs instead?

**Comment by thorerik** [comment]
As far as I can tell, libjpeg-turbo-progs is a set of applications for modifying jpegs and depends libjpeg8.

The package you want is https://tracker.debian.org/pkg/libjpeg-turbo and should be available, if it isn't I'd investigate what repos you got and why it's not being found.

**Comment by 33mhz** [comment]
Sorry -- new to this. libjpeg-turbo-progs says it depends on libturbojpeg1 and libjpeg62-turbo. Debian.org only finds libjpeg-turbo-progs [when I search](https://packages.debian.org/search?searchon=names&keywords=libjpeg-turbo).

**Comment by m0r13** [comment]
When you search only for libjpeg, it also finds libjpeg62-turbo. Did you get any dependency errors when you installed the package? Even if libpjeg turbo is not available, the package should use the normal libjpeg library ([Debian package control file](https://github.com/mapcrafter/mapcrafter-buildfiles/blob/master/debian/debian/control#L13)) since libjpeg-turbo is a drop-in replacement of libjpeg.

**Comment by 33mhz** [comment]
@m0r13 Yep, I get:

`The following packages have unmet dependencies:
 mapcrafter : Depends: libjpeg-turbo8 which is a virtual package. or
                       libjpeg-turbo which is a virtual package. or
                       libjpeg8 which is a virtual package.
`

libjpeg62-turbo is installed by default on Debian. :/

**Comment by m0r13** [comment]
Oh I see. Virtual package means that there is a specific functionality which can be provided by several different packages (like that jpeg library is provided by the normal library and the enhanced libjpeg turbo library). Seems that they changed the names of those packages a bit. Wait a second, I'll have a closer look at it. You are using Debian Jessy?

**Comment by 33mhz** [comment]
@m0r13 Yeah. Thanks!

**Comment by m0r13** [comment]
Hmm, it seems that Debian Jessie has only [libjpeg62-turbo](https://packages.debian.org/search?suite=jessie&arch=any&searchon=names&keywords=libjpeg) as jpeg library implementation. The older Debian Wheezy doesn't have libjpeg-turbo, but it has libjpeg8 which I used to build the Debian packages. The problem is that I think libjpeg8 and libjpeg62 are probably not compatible. I have to build different packages for different Debian / Ubuntu releases now or downgrade to libjpeg62 which is maybe not very good performance-wise for the older Debians that don't have a libjpeg-turbo implementation.

For now you can build Mapcrafter from source, that should work for you. Just follow the [instructions in the documentation](http://docs.mapcrafter.org/builds/stable/installation.html#building-from-source).

**Comment by 33mhz** [comment]
Thanks -- will do.

**Comment by 33mhz** [comment]
Just FYI, it replaced libpng-dev with libpng12-dev, and built and installed without any errors.

**Comment by m0r13** [comment]
Hey, I finally found the time to restructure the build system. It's supporting building packages for multiple Debian-like distributions/versions now (with separate build control files to solve the issue with different dependencies).

There is a new package repo which is described [in the documentation](http://docs.mapcrafter.org/builds/big-fat-refactoring/installation.html#debian-packages). Feel free to test it and report back if there are any issues.

**Comment by 33mhz** [comment]
@m0r13 Thanks! I will give it a shot in the next week.

**Comment by 33mhz** [comment]
So, I got to it "next week" (today), and the Debian repo is working beautifully. Thanks! :)

**Comment by 33mhz** [comment]
Debian 8/Jessie, FYI.

**Comment by m0r13** [comment]
No problem. There are some issues here too that I will solve "next week". :P
