### ISSUE TITLE
Cropping = Warning: Unknown configuration option (help!)

### ISSUE THREAD

**Issue by Jeff403** [mapcrafter/mapcrafter#183]
Hi having an issue but can't seem to find any other posts with the same issue, seems like it should be simple. Leaving the cropping out and it runs fine, but I don't want the whole map. What am I doing wrong?

Using Win10, Minecraft 1.8.8

I'm trying to crop an area but always getting error (but will still render whole map):
Warning: Unknown configuration option 'crop_min_x'!
Warning: Unknown configuration option 'crop_max_x'!
Warning: Unknown configuration option 'crop_min_z'!
Warning: Unknown configuration option 'crop_max_z'!

mapcrafter -c omicron.conf

--conf
output_dir = Omicron Persia 8

[global:map]
world = world
render_view = isometric
render_mode = daylight
rotations = top-left bottom-right
texture_size = 12
crop_min_x = 0
crop_max_x = 200
crop_min_z = 350
crop_max_z = 550

[world:world]
input_dir = C:\Users\Jeff\AppData\Roaming\.minecraft\saves\Omicron Persia 8

[map:world_isometric_day]
name = Normal World - Day

[map:world_isometric_cave]
name = Normal World - Cave
render_mode = cave

**Comment by Jeff403** [comment]
got it,

options need to be under [world:world] for all the others windows users who read the typicallinux-badatdocumenting-butgreatatprogramming guides. :)

**Comment by m0r13** [comment]
Hey, yes, the cropping options are part of the world section as described in the [documentation](http://docs.mapcrafter.org/builds/stable/configuration.html#world-options). The blue box says that these options belong to the world sections. :)

I can understand that my documentation is maybe not that straight forward for some users sometimes as my point of view as a developer might be a bit different. You are free to edit and improve the documentation. I'm trying hard to make the documentation complete and understandable, that's why I'm always happy about pull requests, instead of just complaints that the documentation is too difficult.

There are already issues about the world options and a "too difficult documentation": #162 and #175.
