### ISSUE TITLE
[Help] Render Custom Blocks

### ISSUE THREAD

**Issue by vpant** [mapcrafter/mapcrafter#217]
Hello,

I am trying to add some custom blocks in the map crafter. I added my block to the blocktextures.cpp and blocktextures.h files and I build and rendered my map but it is still not render the custom blocks like you can see in this image
![city](https://cloud.githubusercontent.com/assets/11424758/14382345/b428e8ec-fd95-11e5-95b0-97b02336d627.png) . Do I need to edit any other file in  order to make it work? Is this Feature in your TODO list ?

Thanks in advance for your help and keep up the good work. :)

**Comment by m0r13** [comment]
Hey @vpant, there are also some other places you have to consider when adding new blocks. At the moment there is also another issue open with the same question (#197). I'm sorry I didn't find the time yet to write a bit about it, but I'll try to assemble a little list with places you have to consider when adding your own blocks today or tomorrow.

**Comment by vpant** [comment]
That would be very helpful. Thank you very much :)

**Comment by m0r13** [comment]
Okay, so here is a rough overview: Each render view has to implement a class which provides the block images. That's ``BlockImages`` or ``AbstractBlockImages`` (in [src/mapcraftercore/renderer/blockimages.h](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/blockimages.h) and [.cpp](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/blockimages.cpp)). The classes are documented so you can read that a bit to get an rough idea how the block images are generated / stored.

The implementations of the block image classes are in [renderer/renderviews/isometric/blockimages.h](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/renderviews/isometric/blockimages.h) and [.cpp](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/renderviews/isometric/blockimages.cpp) for the isometric render view and in [renderer/renderviews/topdown/blockimages.h](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/renderviews/topdown/blockimages.h) and [.cpp](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/renderviews/topdown/blockimages.cpp) for the topdown render view.

You will find a method ``createBlocks`` where all the blocks are created and where you can add your own blocks. Just look how different existing blocks are created.

Regarding block data the method ``filterBlockData`` is important. It is used by the block images classes to ignore block data that is not used for the rendering. Also there is data that depends on the neighbor blocks and is not represented by the MC block data (connection of fences for example). This data is added to the MC block data in the ``TileRenderer::checkNeigbors``-method in [renderer/tilerenderer.cpp#L125](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/tilerenderer.cpp#L125) and can be used as regular data in the block images class.

Biome blocks are created as usual in the ``createBlocks``-method too, but then are handled by the ``createBiomeBlock``-method. You can have a look at how ``IsometricBlockImages`` handles this ([renderer/renderviews/isometric/blockimages.cpp#L1832](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/renderviews/isometric/blockimages.cpp#L1832)). A block is handled as biome block if ``Biome::isBiomeBlock`` returns true ([renderer/biomes.cpp#L116](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/biomes.cpp#L116)).

Last but not least, some transparent blocks might have incorrect lighting data which must be corrected by the lighting render mode, otherwise these blocks will look black with lighting: [renderer/rendermodes/lighting.cpp#L109](https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/rendermodes/lighting.cpp#L109).

That should be about it what you should know about how the block images are created and handled. If you have further questions or something doesn't work, don't hesitate to ask. :)

**Comment by m0r13** [comment]
I forgot Minecraft textures: They are defined in [https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/blocktextures.h](renderer/blocktextures.h) and [https://github.com/mapcrafter/mapcrafter/blob/d3af7f30a17af6dac71ba15dfe98f80041c06d93/src/mapcraftercore/renderer/blocktextures.cpp](.cpp). These files are automatically generated by a script. Just place all your needed textures in ``src/data/textures`` and run ``make gen_texture_code`` and all PNGs in that directory will be added to that class.

**Comment by vpant** [comment]
Hey @m0r13 your tutorial was perfect and so easy to follow. I just make it work without any problems. Thank you so very much. May I suggest to write this guide for adding custom blocks in the docs (docs.mapcrafter.org) so anyone can have easy access to this information?

**Comment by m0r13** [comment]
Yup, I got that idea too that a development section (also about other topics) might be useful in the docs. I'll have a look at that.

**Comment by vpant** [comment]
Ok that is nice. One more thing, after sudo make install is there any way to unistall mapcraft, because after that if I change anything to the source code and try to rebuild my changes does not take place.

**Comment by m0r13** [comment]
There is no ``make uninstall`` target per default, but CMake should write a file ``install_manifest.txt`` with installed files which you can delete. Your changes should take place when you do ``make install`` again, as the files will be overwritten. I would recommend you not to install Mapcrafter when doing development work with it, but just to run ``src/mapcrafter``.

**Comment by vpant** [comment]
Thanks for you answer. I am not familiar with linux operating systems and in learning mode :) . I google it and found I could use sudo checkinstall instead of sudo make install. It creates a package gets installed and then you can remove it by executing sudo dpkg -r mapcrafter. Thanks again for all your help :)

**Comment by m0r13** [comment]
Will be mostly fixed with Mapcrafter version for Minecraft 1.13, as block images are automatically generated.
