### ISSUE TITLE
Dependency problem in Ubuntu 14.04

### ISSUE THREAD

**Issue by filippogasbarro** [mapcrafter/mapcrafter#246]
Here the output of the installation in Ubuntu 14.04 with the .deb in the website. The problem is that the software search for the software libboost-iostreams1.58.0, libboost-system1.58.0 etc. but in Ubuntu 14.04 repository there is the package name without the name of the version at the end of the name
```
Unpacking mapcrafter (2.3.1-1) ...
dpkg: dependency problems prevent configuration of mapcrafter:
 mapcrafter depends on libboost-iostreams1.58.0; however:
  Package libboost-iostreams1.58.0 is not installed.
 mapcrafter depends on libboost-system1.58.0; however:
  Package libboost-system1.58.0 is not installed.
 mapcrafter depends on libboost-filesystem1.58.0; however:
  Package libboost-filesystem1.58.0 is not installed.
 mapcrafter depends on libboost-program-options1.58.0; however:
  Package libboost-program-options1.58.0 is not installed.

dpkg: error processing package mapcrafter (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mapcrafter
```

**Comment by m0r13** [comment]
Are you sure that you downloaded the Debian package for ubuntu 14.04 (Trusty) ? According to the [build files](https://github.com/mapcrafter/mapcrafter-buildfiles/blob/master/debian/control.sh#L64) Boost 1.55 should be used for Ubuntu 14.04 which should be available.

Also installing Mapcrafter from the Debian package repo works for me in a docker container and is the preferred way to install Mapcrafter. I would advise you to try that.

**Comment by m0r13** [comment]
Debian package repo: https://docs.mapcrafter.org/builds/stable/installation.html#debian-packages

**Comment by filippogasbarro** [comment]
Yes, before I wrong to download, but now I've retried to download the right one Trusty 14.04 64 bit version of the .deb file and Ubuntu 14.04.5 64bit version of the .iso and all dependencies of liboost are at version 54, instead the .deb file want the version 55, that doesn't exists in repository

**Comment by m0r13** [comment]
Which version of Ubuntu are you using now?

Please try to use the Debian package repo instead of downloading the file manually from the website:

```
echo "deb http://packages.mapcrafter.org/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/mapcrafter.list
sudo wget -O /etc/apt/trusted.gpg.d/mapcrafter.gpg http://packages.mapcrafter.org/ubuntu/keyring.gpg
sudo apt-get update
sudo apt-get install mapcrafter
```

**Comment by filippogasbarro** [comment]
Like written in last comment I'm using Ubuntu 14.04.5 64bit
Unfortunately, also by using the repo, instead of the .deb file, the problem persists :/
![screenshot](https://cloud.githubusercontent.com/assets/15571375/22076641/32af8c6a-ddb1-11e6-96c1-85448d530f5b.png)

**Comment by Held03** [comment]
Just for curiosity, I did some research into this matter. And setup a fresh virtual machine with Ubuntu Trusty 14.04.5 (64bit desktop version).

I started by installing Mapcrafter from the repository (as recommended [here](https://github.com/mapcrafter/mapcrafter/issues/246#issuecomment-273538419)) and it worked well since the Boost library 1.55 is indeed in the Trusty repository and got just installed by `apt-get`.

However, the Boost library 1.54 is also in the repository and the somewhat preferred version e.g. by the meta packages. So I suspected that 1.54 might have caused the problem. I try it by first removing Mapcrafter and Boost 1.55 again and installing explicitly Boost 1.54. However, installing Mapcrafter again worked well and I ended up having both installed Boost 1.54 and 1.55. I'm not sure if this is a bug. Anyway Mapcrafter seemed to work (as far as I tested it).

Next I cleaned both Boosts and Mapcrafter again and tried this time to install the Xenial 16.04 .deb (which is the wrong version) with `dpkg` first, which failed as expected with the same error message as in the [initial post](https://github.com/mapcrafter/mapcrafter/issues/246#issue-194802207). However, `dpkg` leaves the system in a somewhat broken state, as determined by `apt-get check`:

```
$ sudo apt-get check
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 mapcrafter : Depends: libboost-iostreams1.58.0 but it is not installable
              Depends: libboost-system1.58.0 but it is not installable
              Depends: libboost-filesystem1.58.0 but it is not installable
              Depends: libboost-program-options1.58.0 but it is not installable
E: Unmet dependencies. Try using -f.
```

So trying to install Mapcrafter from the repository without fixing the package system results for me in a similar error as in the [preceding comment](https://github.com/mapcrafter/mapcrafter/issues/246#issuecomment-273553522):

```
$ sudo apt-get install mapcrafter
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 mapcrafter : Depends: libboost-iostreams1.55.0 but it is not going to be installed
              Depends: libboost-system1.55.0 but it is not going to be installed
              Depends: libboost-filesystem1.55.0 but it is not going to be installed
              Depends: libboost-program-options1.55.0 but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

Well, the error message is quiet distinct. However, I could fix that state easily by running the recommended command `apt-get -f install` which fixes the package mess and installs Mapcrafter as earlier intended.

Finally, I'm not sure if this would also fix @filippogasbarro problem, but even if not, this issue seems not to be the fault of Mapcrafter since it works well on a fresh installation. And I would recommend to close this issue.
