### ISSUE TITLE
(World113): Waterlogged Top Slabs & Water Surface

### ISSUE THREAD

**Issue by Sicarine** [mapcrafter/mapcrafter#293]
**Mapcrafter Version "mapcrafter_2.3.1 ~125~ gd8bf148_win64"**

There is an issue with the appearance of waterlogged top slabs. Specifically, the top slabs in the topmost layer of a body of water will also have a blue overlay, thus appearing as if they are submerged in a few millimeters of water.

Apologies in advance for the click-bait-style arrow

In the image below, The water is a 3-layer deep pool from y=1 to y=3. The dark oak bench, the hay bale, the pumpkin, and the crafting table are blocks at y=4. There is a pier made of waterlogged top slabs at y=3, immediately below these blocks, thus also coinciding with the top water layer.

![waterlog_top_slab](https://user-images.githubusercontent.com/43017668/46976428-7bc5cd80-d097-11e8-9ea1-18ae190e97b3.png)

The same scene in game:

![2018-10-15_16 43 32](https://user-images.githubusercontent.com/43017668/46977265-b7fa2d80-d099-11e8-99c9-135efdf73aaa.png)

**Comment by m0r13** [comment]
I was aware of the issue. I thought it's a small detail but in that case it's quite visible. The problem is that water on top of waterlogged blocks is rendered in Mapcrafter by just blending the water on top of the block image, and there is no check if parts of the block should be outside of the water. I used to render the water surface of waterlogged blocks for each block in Blockcrafter, but now that water is handled as a biome block, I moved that to Mapcrafter. Luckily I think there might be an easy check possible for slabs, stairs, etc. to fix this.

**Comment by m0r13** [comment]
You can test it with the current commit.

**Comment by Sicarine** [comment]
I may need to wait for a nightly package. I uh...lack the technical know-how to build it on my windows.

**Comment by shelterx** [comment]
Fixed for me anyway.

**Comment by m0r13** [comment]
@Sicarine there was a small problem with the build system not being triggered properly automatically when they were changes. I think I fixed it. Feel free to remind me again tomorrow if there is no new package built tonight. :)

https://buildbot.mapcrafter.org/#/builders
