### ISSUE TITLE
Get output as single png?

### ISSUE THREAD

**Issue by vbgfhfngfdtyreyt** [mapcrafter/mapcrafter#294]
Hello,

I am interested in getting the output rendered as a single png. I realize this could be a huge file, but it's perfect for printing out on a poster, for example.

Is there an option for this? 

Thank you!

**Comment by taziup** [comment]
I think you can use the python script in tools 
https://github.com/mapcrafter/mapcrafter/blob/master/src/tools/mapcrafter_png-it.py

**Comment by m0r13** [comment]
@vbgfhfngfdtyreyt 
The script @taziup mentioned is the way which is possible right now.

**Comment by vbgfhfngfdtyreyt** [comment]
Thank you!

**Comment by Berghopper** [comment]
@m0r13 I know this is a closed issue, and maybe my question is a bit off topic, but here we go;

Would it be in any way possible to make the intermediary/smallest pngs a little bigger as to prevent the huge amount of files? Random Disk IO tends to be pretty slow on hard drives, and since mapcrafter outputs take up a lot of spaces, I don't think they are saved on SSDs an awful lot.
