### ISSUE TITLE
What are some alternatives for Mapcrafter?

### ISSUE THREAD

**Issue by EladKarni** [mapcrafter/mapcrafter#383]
I used mapcrafter a few years ago, and haven't touched it since. I recently started a new server and would love a way to show the entire world via a website in a 3D way to the active users.

I tried using Mapcrafter, but since the server is running on the most up to date version, it kept crashing, and it seems like updates for this project has stopped a few years ago. What other options out there would you recommend?

Cheers!

**Comment by taziup** [comment]
Hello,

you can use miclav world116 branch (from his fork). He's pretty active.

I remember there is a pending pull request to update here, but it hasn't merge yet.

https://github.com/miclav/mapcrafter/tree/world116

**Comment by oskarkk** [comment]
Most of the potential users of Mapcrafter don't know how to navigate Github, and while it's quite easy, most of them will just seek other alternatives. When you tell them to compile the newest version of Mapcrafter (god forbid with some patches or something!), 90% will pass and won't look at Mapcrafter ever after. Actually, Mapcrafter was the first software I compiled from Github, and I only did it because I've made a config file for an earlier version and I've invested some time to write it, so I didn't want to migrate to Minecraft Overviewer or something. If you want people to use Mapcrafter, do something to merge it to master, or just fork it, name it "Mapcrafted" or something, and make a new "brand" and work on it. In the eyes of most of the users looking for Minecraft mappers, Mapcrafter wasn't updated in 3 years. That's just sad, considering that many people put significant work in keeping it up to date.

**Comment by EladKarni** [comment]
Not really sure if you are talking about me or in general oskarkk.

Thanks taziup! I'll check it out

**Comment by elamperti** [comment]
As @taziup mentioned, there's miclav's fork which has updates up to 1.16. He's been making updates for the latest versions. They are also reflected in the [world113 branch](https://github.com/mapcrafter/mapcrafter/pull/279), and it's available to download it packaged for Windows from the [_nightly_ downloads](https://mapcrafter.org/downloads/nightly). This one should work for version 1.16 (and below).

Addressing @oskarkk's message: I understand your frustration as a user. I've been doing some efforts to move things forward as maintainer and sadly I've been caught up with more pressing -personal- things. Keep in mind that every person collaborating on this project is giving their time for free, so even we try to keep things working, sometimes just there isn't enough time. If you see a tangible, direct way things can be improved, you are welcome to open a pull request with improvements. We'll eventually get `world113` merged to master. In any case, thanks for sharing your concern! :)

**Comment by EladKarni** [comment]
Thanks for the reply @elamperti and feedback.

I'll check out those nightly releases you linked to and give them a shot and report back if it works on the latest release

**Comment by oskarkk** [comment]
@EladKarni I'm talking in general, as there have been many issues here that resulted from the newest version being "hidden" and undocumented.

@elamperti, I don't know much about development processes, so sorry if I'm ignorant, but why can't you "just" merge it? Isn't that like a couple of clicks on Github? I know that world113 isn't perfect, but what keeps you from merging it, numbering a new version like "3.0", and putting eventual fixes to release "3.0.1"? Then making a new release for every version of Minecraft, rather than just leaving commits hanging in the air in this branch, and confusing new users? I think that having a quite unstable version on master is better than having users trying to run 2.4 on 1.16 worlds or discarding Mapcrafter altogether after seeing that it's (seemingly) not updated anymore.

> They are also reflected in the [world113 branch](https://github.com/mapcrafter/mapcrafter/pull/279), and it's available to download it packaged for Windows from the [_nightly_ downloads](https://mapcrafter.org/downloads/nightly).

I know, but nightly builds have stopped for Linux, so I had to compile it myself. I've run into some problems doing it, but finally I've made it.

> Keep in mind that every person collaborating on this project is giving their time for free, so even we try to keep things working, sometimes just there isn't enough time. If you see a tangible, direct way things can be improved, you are welcome to open a pull request with improvements.

I understand, and I'm grateful to all of you for your work, and sorry if I sound like I demand something. I just don't understand why some simple things can't be done to help users find and use the newest versions. I know almost nothing about C++, mayyybe I could do something in Python or make some new feature in JS with Leaflet (if things like that are in the scope of Mapcrafter), but certainly I could do something with the documentation. Like putting there links to and description of the world113 version, instructions how to compile that version on Linux etc. The existing instructions for the Mapcrafter 2.4 would go to the separate page in these updated docs (someone's surely using Minecraft 1.12). But the question is, would these new docs appear on the Mapcrafter's webpage, or at least be incorporated into the readme of the master branch? They wouldn't be very useful if they could be found only as a file somewhere on the Github repo, on a branch described as "Minecraft 1.13" - version that is 2.5 years old.

Thanks for your time!

**Comment by taziup** [comment]
> @elamperti, I don't know much about development processes, so sorry if I'm ignorant, but why can't you "just" merge it? 
> 

world113 branch is not compatible with minecraft 1.12 and less (cause of chunk format changes) and the idea was to keep the master branch for minecraft 1.12 and before and world113 branch for minecraft 1.13 and more.

**Comment by skylerwlewis** [comment]
@taziup I was under the impression that world113 was only separate until it was 100% working, which I believe it either already is or is close to being ready from what I have seen. After it is working, it should be merged into master (see [PR](https://github.com/mapcrafter/mapcrafter/pull/279)). If master and world113 have so many separate changes that they shouldn't be merged together, then I think they should be (ideally) split off into separate projects if they both have ongoing development. I think the last checkbox item in the PR is to package legacy mapcrafter (pre-1.13) separately, not sure if that has been thought through though.

**Comment by bemk** [comment]
@oskarkk I wish it was as simple as just hitting the merge button on some merge request. The trouble is that while the changes made in mine and miclav's repository do indeed render any minecraft version between 1.13 and 1.17, they are incompatible with the world formats for 1.12 down and 1.18 up. Merging these changes would break the build for people using mapcrafter on older versions.

We could do any of the following 3 things to fix this.

1. Split the product into multiple different editions, one for each range of minecraft version supported.
2. Create a behaviour pattern architecture that allows the user to configure for which minecraft version they're rendering, or
3. Effectively the same as 2 but now there's extra code that automatically detects which file format is being used to make it transparent to the user.

Option 1 is simplest, and is effectively already happening with the split between miclav's version and the official release. Option 2 would make everyone unhappy as it requires more work from the users, and option 3 would be easiest for regular users.

At any rate, there's still a lot of work to be done before this can get merged, and unfortunately, I only really have the time to "make it work for me."

I hope this explains the situation.
