### ISSUE TITLE
Copyright of Textures/Blocks images for a repository? 

### ISSUE THREAD

**Issue by SkibbleBip** [mapcrafter/mapcrafter#390]
I'm planning on adding Mapcrafter to the repository for TinyCore and will be splitting the project up into 3 separate packages (or "extensions", as they are referred to by TinyCore): mapcrafter, mapcrafter-template, and mapcrafter-blocks. I wanted to ask first before adding the blocks extension, if the copies of the block images generated by mapcrafter tools from the textures of Minecraft would be copyrighted by Mojang and therefor not be allowed to be distributed through a repository?

The current textures I am using come from bemk (https://github.com/bemk/mapcrafter/tree/world117/src/data/blocks)'s fork (which I am pretty sure is also just the master's blocks) and I am using their fork of the world117 branch, as theirs is what I consider the most "compatible" with the "latest" version of Minecraft (which was 1.17.1 at the time of me starting working of developing these extensions, I will update to 1.18 once a fix to #388 's incompatibilities with 1.17 and 1.18 is fixed).

**Comment by elamperti** [comment]
The textures are extracted from the game files, so I'd suggest to avoid redistributing them. That said, it's quite common to see mapping tools do this, and Mojang doesn't seem to care (probably because maps are derivate products of the game, in a way; and the textures are being used fairly -i.e. it's clear that they are from the game and not part of the mapping tool-).

To avoid any possible issue, the ideal process would be to generate the textures with blockcrafter before mapcrafter is used.

For blockcrafter in particular, consider using the dockerfile instead of compiling binaries, as it requires very specific versions of libraries (it breaks horribly with newer/different versions).

I also recommend you to check out miclav's forks as well (he's a big contributor on 1.13+ changes)

**Comment by SkibbleBip** [comment]
I see, thank you for the information.
