### ISSUE TITLE
Corner stairs not showing proper rotation

### ISSUE THREAD

**Issue by gmr** [mapcrafter/mapcrafter#59]
Screenshot from overviewer: 
![http://i.imgur.com/e4ac9Bz.png](http://i.imgur.com/e4ac9Bz.png)

Screenshot from mapcrafter v1.1.3: 
![http://i.imgur.com/pFVaYKr.png](http://i.imgur.com/pFVaYKr.png)

Note the missing blocks are the new 1.8 snapshot blocks, not including in this ticket.

Love the speed and simplicity of the app, looking forward to your planned new features :)

**Comment by m0r13** [comment]
I finally got some time and motivation to work on this annoying problem, it wasn't easy, but I was able to implement the corner stairs. You can find it in the ``corner-stairs-wtf`` branch if you want to try it. Otherwise have a look at the [exmaple](http://exmaple.mapcrafter.org).

There is still a little problem with the new stairs... Some stairs are wrong, but the corner stairs are mostly working. I will try to fix this and then I will merge the branch.

**Comment by m0r13** [comment]
And it's fixed and merged now.
